In [166]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")

In [167]:
#Read the exports of commodities to European Union file.
exp = pd.read_excel('EXP_2001_2019_20230306.xlsx')
exp = pd.DataFrame(exp)

In [168]:
exp

,Bloco Econômico,Código CUCI Subgrupo,Descrição CUCI Subgrupo,2019 - Quilograma Líquido,2018 - Quilograma Líquido,2017 - Quilograma Líquido,2016 - Quilograma Líquido,2015 - Quilograma Líquido,2014 - Quilograma Líquido,2013 - Quilograma Líquido,...,2010 - Quilograma Líquido,2009 - Quilograma Líquido,2008 - Quilograma Líquido,2007 - Quilograma Líquido,2006 - Quilograma Líquido,2005 - Quilograma Líquido,2004 - Quilograma Líquido,2003 - Quilograma Líquido,2002 - Quilograma Líquido,2001 - Quilograma Líquido
0,União Europeia - UE,2222,Soja,4792451962,4698634925,4547239449,4886427014,5248786739,5838800600,4686635386,...,5323694271,8030825380,8390080582,9038979393,9369967530,10343034568,8675662962,10134615813,8649214058,9341767324
1,União Europeia - UE,711,"Café não torrado, mesmo descafeinado",1080687572,916186562,839182414,949289319,983893282,1044126514,878985329,...,970813317,914302608,943683776,870639919,866096923,788667643,857949250,772096805,919794460,757728639
2,União Europeia - UE,6343,"Madeira compensada, madeira folheada e madeira...",325345123,415149255,345826218,312419850,333666597,319363809,304182354,...,312432041,279475299,420149404,458423862,359205540,321559225,447488447,391075713,324577905,321169234
3,União Europeia - UE,2461,Madeira em estilhas ou em partículas,257633164,362654212,133972450,219636070,139045980,161790340,83463300,...,85443990,66401500,126233750,83371420,53083413,110946040,93034970,56412938,69965890,98260320
4,União Europeia - UE,2462,"Serragem e resíduos de madeira e sucata, mesmo...",161027155,74730428,56059374,35567779,24396234,6368880,173194,...,219300,558000,535656,6095644,135792449,76858500,121958030,100510300,0,0
5,União Europeia - UE,6114,Couros e peles de bovinos (incluindo os búfalo...,138934626,140283349,138079219,122038270,112375685,103306550,139421219,...,114980347,98130387,98196857,125198789,145662696,115496407,127562649,128024755,138137023,140048630
6,União Europeia - UE,2484,Madeira de espécies não coníferas especificada...,114988728,120586757,95350131,97195566,87173861,95531553,76263274,...,161846357,158340219,313489167,540378258,464442663,552296663,606318337,462262284,395015307,370082392
7,União Europeia - UE,2485,"Madeira de espécies não coníferas, perfilada (...",96019935,72423337,65948652,64702876,69719566,63633154,54687545,...,116829167,106525930,160490581,228997130,166173347,123508108,111098216,65756167,39196548,33477699
8,União Europeia - UE,2479,Outras madeiras em bruto ou simplesmente esqua...,69059930,594602,194981,122069,69694,51911,25196,...,117237,46847,78818,214518,1548541,677680,0,0,0,15750000
9,União Europeia - UE,112,Carne bovina congelada,40793832,43718862,37177408,35265583,38234859,39618551,41560293,...,23973128,27484019,24029776,100564850,187603411,165913193,127082236,84147684,71716118,69451846
10,União Europeia - UE,2482,"Madeira de coníferas, serrada ou fendida longi...",36221540,30477931,14138193,16394742,6514375,3750232,2727363,...,11863640,17349950,55383232,109797987,63851226,55376452,80943739,102422679,80702777,76095330
11,União Europeia - UE,8215,"Outros móveis, de madeira",25424057,22400772,21724562,21491745,20512764,19997055,21003061,...,64573253,72726607,90670799,103270385,98318346,118696152,126694169,111074141,84405589,72146866
12,União Europeia - UE,6359,Outros artigos manufaturados de madeira,21751293,24141483,20977240,24983697,26190254,37760130,41402460,...,26928547,18828689,23959256,21850899,19839611,19252310,19050086,17779569,16403471,13161050
13,União Europeia - UE,111,Carne bovina fresca ou refrigerada,19702721,21801700,22521828,25643749,24742948,25490428,23643956,...,18653962,16216436,8996213,73048431,68586642,65175026,57199559,44834561,33696590,31938888
14,União Europeia - UE,6349,"Madeira, em forma simples",14713967,10293944,7540989,7460870,7051402,4322506,3386056,...,4901806,9813275,14664386,22865138,26133217,20219436,24284943,5330028,62793,2225
15,União Europeia - UE,6345,Painéis de fibras de madeira ou de outras maté...,12245297,33472869,15472520,16166147,13657118,12317848,11367710,...,36849575,43069858,45912933,59471350,49897565,57844546,56257939,58656934,50147580,47168521
16,União Europeia - UE,713,"Extratos, essências e concentrados de café e p...",10437724,7191433,8089148,11069586,10342210,9609652,10236102,...,11353043,8765490,16054229,13582598,14830546,15412422,15130049,14081733,14486700,15111833
17,União Europeia - UE,2450,Lenha (excluindo resíduos de madeira) e carvão...,8849163,708361,241306,2760154,158360,0,0,...,687545,3333606,2693266,6589658,6919476,4276213,11559288,9704335,6197398,3987050
18,União Europeia - UE,6342,"Madeira densificada e painéis de partículas, p...",3589138,3013195,2410792,1771506,894548,513430,105084,...,4109051,7764479,17593350,40318292,21643722,17133476,15907321,7510713,7560708,13505712
19,União Europeia - UE,6341,"Folhas para folheados,folhas para contraplacad...",2471983,1919272,2932381,2590317,2559899,2122527,2113722,...,3631833,3373400,6670576,11880097,13160568,15762796,14671500,12403355,11055758,10854891
20,União Europeia - UE,2322,"Borracha reconstituída, desperdícios e resíduo...",2336266,3698720,4680450,6236000,5423294,4017130,2592218,...,2506300,3001440,3165480,3572008,3306090,3732607,3993300,4008605,5536420,5596100
21,União Europeia - UE,2483,"Madeira de coníferas, perfilada (com espigas, ...",1561179,1755129,1431736,1079364,1277915,901244,1553809,...,8023970,3832161,5869670,7335816,2326497,4121762,1342721,1564409,2099432,2114912
22,União Europeia - UE,6211,"Borracha misturada, não vulcanizada, em formas...",1493042,834501,322358,578722,517388,509533,430015,...,469703,686431,918611,814926,504847,679315,509963,320670,269793,194215
23,União Europeia - UE,4211,Óleo de soja e respectivas frações,997853,719254,462688,279738,433450,1792575,26054830,...,58506871,178547611,515756627,527571430,865273306,235063700,75860931,32248460,5195928,12602430
24,União Europeia - UE,6299,"Disco de borracha, obras de borracha endurecid...",564962,817952,768683,591967,627222,627119,787722,...,644228,488860,1807750,1690780,1991568,2204797,1464424,702924,782958,748136
25,União Europeia - UE,4222,Óleo de palma e suas frações,538056,12672936,24041921,39245248,92071992,60274972,70911185,...,7985037,8213582,6094148,3493,1132646,6177579,9982631,511891,2259262,10859394
26,União Europeia - UE,6354,Manufaturas de madeira para uso doméstico ou d...,278158,56740,13726,26573,27584,22568,24511,...,227489,223934,166124,600350,978302,826324,1349646,857143,493984,445998
27,União Europeia - UE,6214,"Tubos, canos e mangueiras, de borracha vulcani...",270059,70107,84625,62114,104368,96011,122689,...,100962,127283,196355,194503,565037,411167,467125,500040,414268,290977
28,União Europeia - UE,6213,"Fios e cabos de borracha vulcanizada , chapas,...",258164,315793,377591,320502,383009,354671,347651,...,647679,469029,650141,756089,835928,965717,2202691,1668634,1034875,1066579
29,União Europeia - UE,2474,"Madeira de coníferas, em bruto (mesmo descasca...",175335,2643,0,0,0,0,0,...,0,0,0,0,292800,9686290,44406182,10495510,333991728,335540667
30,União Europeia - UE,712,Café torrado,46622,63399,129881,444640,464582,285164,249543,...,1096787,998510,1101161,1045790,1152363,1261792,988523,570154,394917,65294
31,União Europeia - UE,6292,"Correias transportadoras ou de transmissão, de...",22756,71177,101616,55298,1538214,20538,47217,...,103778,71724,95469,131964,115161,353021,459059,288942,128079,132849
32,União Europeia - UE,6212,"Outras formas (ex. varetas, tubos, perfis) e a...",9193,20546,25059,90763,104228,101637,124681,...,217138,135522,121187,32201,33999,34086,16648,13628,3782,3717
33,União Europeia - UE,175,"Carne e miudezas (exceto fígado) de bovinos, p...",7383,2011,0,0,0,0,0,...,0,0,0,0,0,0,240,1054,0,4435
34,União Europeia - UE,2311,"Látex de borracha natural, mesmo pré-vulcanizado",194,95,20,27,1276,993,28,...,180,197,75,368,33,0,49,2790,0,1
35,União Europeia - UE,2312,Borracha natural (exceto látex),17,178,27810,127,29,1,4,...,1,4,52,9,15,0,0,0,0,0
36,União Europeia - UE,2475,"Madeira de espécies não coníferas, em bruto (m...",0,85940,35839,0,0,0,0,...,544899,565018,440832,392214,383500,872950,3405000,1022400,4004429,6608500
37,União Europeia - UE,2112,Couros e peles de bovinos (incluindo os búfalo...,0,3960,75629,370720,245860,118015,189747,...,69511,25888,21700,92285,332148,639260,569272,1047951,2493334,2099901
38,União Europeia - UE,2473,Madeira em bruto (mesmo descascada ou alburno)...,0,0,0,0,0,21000,21000,...,0,0,0,0,0,0,0,212000,130000,52000
39,União Europeia - UE,2481,Dormentes de madeira ou dormentes transversais,0,0,0,0,0,0,0,...,0,1111752,3998703,1708515,1346908,615067,747323,202642,0,0

In [169]:
#Isolating the wood exports.
wood = exp["Descrição CUCI Subgrupo"].str.contains("madeira|carvão", case=False)
wood = exp[wood]
wood

,Bloco Econômico,Código CUCI Subgrupo,Descrição CUCI Subgrupo,2019 - Quilograma Líquido,2018 - Quilograma Líquido,2017 - Quilograma Líquido,2016 - Quilograma Líquido,2015 - Quilograma Líquido,2014 - Quilograma Líquido,2013 - Quilograma Líquido,...,2010 - Quilograma Líquido,2009 - Quilograma Líquido,2008 - Quilograma Líquido,2007 - Quilograma Líquido,2006 - Quilograma Líquido,2005 - Quilograma Líquido,2004 - Quilograma Líquido,2003 - Quilograma Líquido,2002 - Quilograma Líquido,2001 - Quilograma Líquido
2,União Europeia - UE,6343,"Madeira compensada, madeira folheada e madeira...",325345123,415149255,345826218,312419850,333666597,319363809,304182354,...,312432041,279475299,420149404,458423862,359205540,321559225,447488447,391075713,324577905,321169234
3,União Europeia - UE,2461,Madeira em estilhas ou em partículas,257633164,362654212,133972450,219636070,139045980,161790340,83463300,...,85443990,66401500,126233750,83371420,53083413,110946040,93034970,56412938,69965890,98260320
4,União Europeia - UE,2462,"Serragem e resíduos de madeira e sucata, mesmo...",161027155,74730428,56059374,35567779,24396234,6368880,173194,...,219300,558000,535656,6095644,135792449,76858500,121958030,100510300,0,0
6,União Europeia - UE,2484,Madeira de espécies não coníferas especificada...,114988728,120586757,95350131,97195566,87173861,95531553,76263274,...,161846357,158340219,313489167,540378258,464442663,552296663,606318337,462262284,395015307,370082392
7,União Europeia - UE,2485,"Madeira de espécies não coníferas, perfilada (...",96019935,72423337,65948652,64702876,69719566,63633154,54687545,...,116829167,106525930,160490581,228997130,166173347,123508108,111098216,65756167,39196548,33477699
8,União Europeia - UE,2479,Outras madeiras em bruto ou simplesmente esqua...,69059930,594602,194981,122069,69694,51911,25196,...,117237,46847,78818,214518,1548541,677680,0,0,0,15750000
10,União Europeia - UE,2482,"Madeira de coníferas, serrada ou fendida longi...",36221540,30477931,14138193,16394742,6514375,3750232,2727363,...,11863640,17349950,55383232,109797987,63851226,55376452,80943739,102422679,80702777,76095330
11,União Europeia - UE,8215,"Outros móveis, de madeira",25424057,22400772,21724562,21491745,20512764,19997055,21003061,...,64573253,72726607,90670799,103270385,98318346,118696152,126694169,111074141,84405589,72146866
12,União Europeia - UE,6359,Outros artigos manufaturados de madeira,21751293,24141483,20977240,24983697,26190254,37760130,41402460,...,26928547,18828689,23959256,21850899,19839611,19252310,19050086,17779569,16403471,13161050
14,União Europeia - UE,6349,"Madeira, em forma simples",14713967,10293944,7540989,7460870,7051402,4322506,3386056,...,4901806,9813275,14664386,22865138,26133217,20219436,24284943,5330028,62793,2225
15,União Europeia - UE,6345,Painéis de fibras de madeira ou de outras maté...,12245297,33472869,15472520,16166147,13657118,12317848,11367710,...,36849575,43069858,45912933,59471350,49897565,57844546,56257939,58656934,50147580,47168521
17,União Europeia - UE,2450,Lenha (excluindo resíduos de madeira) e carvão...,8849163,708361,241306,2760154,158360,0,0,...,687545,3333606,2693266,6589658,6919476,4276213,11559288,9704335,6197398,3987050
18,União Europeia - UE,6342,"Madeira densificada e painéis de partículas, p...",3589138,3013195,2410792,1771506,894548,513430,105084,...,4109051,7764479,17593350,40318292,21643722,17133476,15907321,7510713,7560708,13505712
19,União Europeia - UE,6341,"Folhas para folheados,folhas para contraplacad...",2471983,1919272,2932381,2590317,2559899,2122527,2113722,...,3631833,3373400,6670576,11880097,13160568,15762796,14671500,12403355,11055758,10854891
21,União Europeia - UE,2483,"Madeira de coníferas, perfilada (com espigas, ...",1561179,1755129,1431736,1079364,1277915,901244,1553809,...,8023970,3832161,5869670,7335816,2326497,4121762,1342721,1564409,2099432,2114912
26,União Europeia - UE,6354,Manufaturas de madeira para uso doméstico ou d...,278158,56740,13726,26573,27584,22568,24511,...,227489,223934,166124,600350,978302,826324,1349646,857143,493984,445998
29,União Europeia - UE,2474,"Madeira de coníferas, em bruto (mesmo descasca...",175335,2643,0,0,0,0,0,...,0,0,0,0,292800,9686290,44406182,10495510,333991728,335540667
36,União Europeia - UE,2475,"Madeira de espécies não coníferas, em bruto (m...",0,85940,35839,0,0,0,0,...,544899,565018,440832,392214,383500,872950,3405000,1022400,4004429,6608500
38,União Europeia - UE,2473,Madeira em bruto (mesmo descascada ou alburno)...,0,0,0,0,0,21000,21000,...,0,0,0,0,0,0,0,212000,130000,52000
39,União Europeia - UE,2481,Dormentes de madeira ou dormentes transversais,0,0,0,0,0,0,0,...,0,1111752,3998703,1708515,1346908,615067,747323,202642,0,0

In [170]:
#renaming and deleting unecessary columns.
wood = wood.rename(columns={'Descrição CUCI Subgrupo':'Wood'})
wood = wood.drop(columns=['Bloco Econômico', 'Código CUCI Subgrupo'])

In [171]:
#Function to rename the columns according to the years.
def year_func(df):
    for i, col in enumerate(df.columns):
        new_col = col.split()[0]
        df.rename(columns={col: new_col}, inplace=True)
    return df

In [172]:
#Function to create a DataFrame for each commodity.
def product(df, name):
    product = df["Descrição CUCI Subgrupo"].str.contains(name, case=False)
    prod = df[product]
    prod = prod.drop(columns=['Bloco Econômico', 'Código CUCI Subgrupo'])
    prod = year_func(prod)
    prod = prod.sum().to_frame()
    prod = prod.drop(['Descrição'], axis=0)
    return prod

In [173]:
#Apply the function for wood.
wood = product(exp, "madeira|carvão")
wood = wood.rename(columns={0:'Total wood exports'})
wood

     Total wood exports
2019         1151355145
2018         1174466870
2017          784271090
2016          824369325
2015          732916151
2014          728468187
2013          602499639
2012          538658425
2011          688354410
2010          839229700
2009          793340524
2008         1289000503
2007         1703561533
2006         1485337691
2005         1510529990
2004         1780517857
2003         1415253260
2002         1426011297
2001         1420423367

In [174]:
#Apply the function for coffee.
coffee = product(exp, 'Café')
coffee = coffee.rename(columns={0:'Total coffee exports'})
coffee

     Total coffee exports
2019           1091171918
2018            923441394
2017            847401443
2016            960803545
2015            994700074
2014           1054021330
2013            889470974
2012            794868454
2011            937782386
2010            983263147
2009            924066608
2008            960839166
2007            885268307
2006            882079832
2005            805341857
2004            874067822
2003            786748692
2002            934676077
2001            772905766

In [175]:
#Apply the function for rubber.
rubber = product(exp, 'borracha')
rubber = rubber.rename(columns={0:'Total rubber exports'})
rubber

     Total rubber exports
2019              4954653
2018              5829069
2017              6388212
2016              7935520
2015              8699028
2014              5727633
2013              4452225
2012              4837059
2011              4578884
2010              4689969
2009              4980490
2008              6955120
2007              7192848
2006              7352678
2005              8380710
2004              9113259
2003              7506233
2002              8170175
2001              8032574

In [176]:
##Apply the function for palm.
palm = product(exp, 'palma')
palm = palm.rename(columns={0:'Total palm exports'})
palm

     Total palm exports
2019             538056
2018           12672936
2017           24041921
2016           39245248
2015           92071992
2014           60274972
2013           70911185
2012           63261568
2011           37688496
2010            7985037
2009            8213582
2008            6094148
2007               3493
2006            1132646
2005            6177579
2004            9982631
2003             511891
2002            2259262
2001           10859394

In [177]:
##Apply the function for soy.
soy = product(exp, 'soja')
soy = soy.rename(columns={0:'Total soy exports'})
soy

     Total soy exports
2019        4793449815
2018        4699354179
2017        4547702137
2016        4886706752
2015        5249220189
2014        5840593175
2013        4712690216
2012        4905661963
2011        5039373137
2010        5382201142
2009        8209372991
2008        8905837209
2007        9566550823
2006       10235240836
2005       10578098268
2004        8751523893
2003       10166864273
2002        8654409986
2001        9354369754

In [178]:
##Apply the function for meat.
meat = product(exp, 'carne|bovino|couro|animais')
meat = meat.rename(columns={0:'Total meat exports'})
meat

     Total meat exports
2019          199438562
2018          205809882
2017          197854084
2016          183318322
2015          175599352
2014          168533544
2013          204815215
2012          165576376
2011          149699428
2010          157676948
2009          141856730
2008          131244546
2007          298904355
2006          402184897
2005          347223886
2004          312413956
2003          258056005
2002          246043065
2001          243543700

In [179]:
#File containing the cocoa exports number.
cocoa_df = pd.read_excel('EXP_cocoa.xlsx')
cocoa = product(cocoa_df, 'cacau')
cocoa = cocoa.rename(columns={0:'Total cocoa exports'})
cocoa

     Total cocoa exports
2019             5635266
2018             5543345
2017             5964441
2016             7186578
2015            10779873
2014             3877478
2013             3109887
2012             2994511
2011             3643491
2010             3913651
2009             2218184
2008             3440790
2007             6173484
2006             4728620
2005            11796841
2004             9826924
2003            15564044
2002            14770823
2001             6393605

In [180]:
#Concatenate all the commodities.
exports = pd.concat([meat, cocoa, wood, rubber, soy, coffee], axis=1)

In [181]:
#Adjusting the index.
exports = exports.reset_index()
#create a file with the new DataFrame.
exports.to_csv('exports.csv')
exports = exports.rename(columns={'index':'year'})
exports.set_index('year', inplace=True)
exports = exports.iloc[::-1]
exports

,Total meat exports,Total cocoa exports,Total wood exports,Total rubber exports,Total soy exports,Total coffee exports
year,,,,,,
2001,243543700,6393605,1420423367,8032574,9354369754,772905766
2002,246043065,14770823,1426011297,8170175,8654409986,934676077
2003,258056005,15564044,1415253260,7506233,10166864273,786748692
2004,312413956,9826924,1780517857,9113259,8751523893,874067822
2005,347223886,11796841,1510529990,8380710,10578098268,805341857
2006,402184897,4728620,1485337691,7352678,10235240836,882079832
2007,298904355,6173484,1703561533,7192848,9566550823,885268307
2008,131244546,3440790,1289000503,6955120,8905837209,960839166
2009,141856730,2218184,793340524,4980490,8209372991,924066608
2010,157676948,3913651,839229700,4689969,5382201142,983263147
2011,149699428,3643491,688354410,4578884,5039373137,937782386
2012,165576376,2994511,538658425,4837059,4905661963,794868454
2013,204815215,3109887,602499639,4452225,4712690216,889470974
2014,168533544,3877478,728468187,5727633,5840593175,1054021330
2015,175599352,10779873,732916151,8699028,5249220189,994700074
2016,183318322,7186578,824369325,7935520,4886706752,960803545
2017,197854084,5964441,784271090,6388212,4547702137,847401443
2018,205809882,5543345,1174466870,5829069,4699354179,923441394
2019,199438562,5635266,1151355145,4954653,4793449815,1091171918

In [182]:
#Adding three more years. Initially, I would use only up to 2019, because CO2 emissions have data only up to this year. But after applying the VAR model, I realized that adding the latest years would be more beneficial for the model than adding the CO2 emissions.
df7 = pd.read_excel('EXP_2020.xlsx')

In [183]:
#Apply the function for wood.
wood2 = product(df7, 'madeira|carvão')
wood2 = wood2.rename(columns={0: 'Total wood exports'})
wood2

     Total wood exports
2022         2789084023
2021         1887586070
2020         1276985259

In [184]:
#Apply the function for wood.
coffee2 = product(df7, 'Café')
coffee2 = coffee2.rename(columns={0: 'Total coffe exports'})
coffee2

     Total coffe exports
2022          1075145114
2021          1050041310
2020          1160074856

In [185]:
#Apply the function for wood.
rubber2 = product(df7, 'borracha')
rubber2 = rubber2.rename(columns={0: 'Total rubber exports'})
rubber2

     Total rubber exports
2022             31329261
2021             24934554
2020              3038644

In [186]:
##Apply the function for soy.
soy2 = product(df7, 'soja')
soy2 = soy2.rename(columns={0: 'Total soy exports'})
soy2

     Total soy exports
2022        7119229419
2021        8421310136
2020        7725974651

In [188]:
meat2 = product(df7, 'carne|bovino|couro|animais|bovina')
meat2 = meat2.rename(columns={0: 'Total meat exports'})
meat2

     Total meat exports
2022          164653774
2021          161631380
2020          183521508

In [190]:
cocoa2 = product(df7, 'cacau')
cocoa2 = cocoa2.rename(columns={0: 'Total cocoa exports'})
cocoa2

     Total cocoa exports
2022             5088924
2021             4102054
2020             5743666

In [192]:
#Concatenate the last three years of all products.
exports2 = pd.concat([meat2, cocoa2, wood2, rubber2, soy2, coffee2], axis=1)
exports2

,Total meat exports,Total cocoa exports,Total wood exports,Total rubber exports,Total soy exports,Total coffe exports
2022,164653774,5088924,2789084023,31329261,7119229419,1075145114
2021,161631380,4102054,1887586070,24934554,8421310136,1050041310
2020,183521508,5743666,1276985259,3038644,7725974651,1160074856

In [ ]:
#Adjusting the years order.
exports2 = exports2.iloc[::-1]
exports2

In [194]:
#Concatenating both DataFrame.
exports = pd.concat([exports, exports2], axis=0)

In [195]:
exports

,Total meat exports,Total cocoa exports,Total wood exports,Total rubber exports,Total soy exports,Total coffee exports,Total coffe exports
2001,243543700,6393605,1420423367,8032574,9354369754,772905766,NaN
2002,246043065,14770823,1426011297,8170175,8654409986,934676077,NaN
2003,258056005,15564044,1415253260,7506233,10166864273,786748692,NaN
2004,312413956,9826924,1780517857,9113259,8751523893,874067822,NaN
2005,347223886,11796841,1510529990,8380710,10578098268,805341857,NaN
2006,402184897,4728620,1485337691,7352678,10235240836,882079832,NaN
2007,298904355,6173484,1703561533,7192848,9566550823,885268307,NaN
2008,131244546,3440790,1289000503,6955120,8905837209,960839166,NaN
2009,141856730,2218184,793340524,4980490,8209372991,924066608,NaN
2010,157676948,3913651,839229700,4689969,5382201142,983263147,NaN
2011,149699428,3643491,688354410,4578884,5039373137,937782386,NaN
2012,165576376,2994511,538658425,4837059,4905661963,794868454,NaN
2013,204815215,3109887,602499639,4452225,4712690216,889470974,NaN
2014,168533544,3877478,728468187,5727633,5840593175,1054021330,NaN
2015,175599352,10779873,732916151,8699028,5249220189,994700074,NaN
2016,183318322,7186578,824369325,7935520,4886706752,960803545,NaN
2017,197854084,5964441,784271090,6388212,4547702137,847401443,NaN
2018,205809882,5543345,1174466870,5829069,4699354179,923441394,NaN
2019,199438562,5635266,1151355145,4954653,4793449815,1091171918,NaN
2020,183521508,5743666,1276985259,3038644,7725974651,NaN,1160074856
2021,161631380,4102054,1887586070,24934554,8421310136,NaN,1050041310
2022,164653774,5088924,2789084023,31329261,7119229419,NaN,1075145114

In [ ]:
#Convert the new DataFrame in a csv file.
exports.to_csv('exports.csv')